import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";
import Footer from "./Footer";
import { OfferWrapper } from "./OfferWrapper";
import { MobileMenu } from "./MobileMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {/* <OfferWrapper /> */}
        <header className="header-container sticky top-0">
          {/* //logo */}
          <div className="flex items-center justify-between">
            <Link href="/" className="cursor-pointer w-24 p-4 my-auto align-middle items-center"><span className="text-blue-500 text-2xl">10x<span className="text-white text-2xl">AI</span><span className="text-white text-2xl">Bootcamp</span></span></Link>
            <MobileMenu />
            <button className="cta-button-header hidden md:block">Let&apos;s talk</button>
          </div>
        </header>
        {children}
        <Footer />
    </>
  );
}
