import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MobileMenu } from "./MobileMenu";
import { OfferWrapper } from "./OfferWrapper";
import Footer from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Define navigation links
  const links = [
    { text: "About me", href: "/#whoami" },
    { text: "My work", href: "/#mywork" },
    { text: "Blog", href: "/blog" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OfferWrapper />
        <header className="header-container sticky top-0 z-10">
          {/* //logo */}
          <div className="flex items-center justify-between">
            <a><span>trip<span className="text-blue-500">rjt</span></span></a>
            <MobileMenu />
            <button className="cta-button-header hidden md:block border border-red-500">Let's talk</button>
          </div>
        </header>
        {children}
        
      </body>
      <Footer/>
    </html>
  );
}
